name: Protoc
#
on: workflow_dispatch
#on:
  #push:
  #  branches:
  #    - 'main'
    #
  #
#
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: abelfodil/protoc-action@v1
        with:
          protoc-version: '3.13.0'
          enable-dart: true
          dart-version: '2.9.2'
      - run: protoc -I. ./protos/github.com/heroiclabs/nakama-common/api/api.proto ./protos/github.com/heroiclabs/nakama-common/api/realtime.proto .protos/grpc-gateway-2.0.0-beta.5/third_party/googleapis/* protos/apigrpc.proto --dart_out=grpc:..lib/src/generated
    #
  #
#
